wso2-ballerina/module-twitter

- .gitignore
- .idea/markdown-navigator.xml
- .idea/vcs.xml
- component/findbugs-exclude.xml
- component/pom.xml
- component/src/main/java/connectors/ConnectorExtensionPackageRepositoryProvider.java
- component/src/org/wso2/ballerina/connectors/twitter/ClientConnector.bal
- pom.xml
Adding Twitter connector implementation. …
> Adding Twitter connector

- component/src/org/wso2/ballerina/connectors/twitter/ClientConnector.bal
Keeping the Ballerina Twitter Connector up-to Date with Ballerina changes.
Fix Twitter connector to support Ballerina version 0.95.3
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
N/A
N/A
N/A
Ballerina version 0.95.3
N/A
> Fixed to support Ballerina 0.95.3

- component/pom.xml
- pom.xml
Pom version changed
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Pom version changed

- pom.xml
module tag added in pom for release purpose
Release the connector
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> module tag added in pom

- component/src/org/wso2/ballerina/connectors/twitter/ClientConnector.bal
- pom.xml
Keeping the Ballerina Twitter Connector up-to Date with Ballerina changes.
Fix Twitter connector to support Ballerina version 0.95.4
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
N/A
N/A
N/A
Ballerina version 0.95.4
N/A
> Fix Twitter connector to support Ballerina version 0.95.4

- tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_transformers.bal
Refactor the connectors as an endpoint
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
N/A
N/A
N/A
N/A
N/A
> Refactor the connectors as an endpoint

- twitter/twitter_objects.bal
> Doc change

- twitter/twitter_connector.bal
- twitter/twitter_objects.bal
> Add changes on implementation

- twitter/Package.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_objects.bal
> Rename TwitterClient to Client and Add changes on Twitter error object

- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
Add changes to support Ballerina version beta0. …
> Add changes to support Ballerina version beta0

- twitter/twitter_connector.bal
- twitter/twitter_types.bal
> Formatting changes

- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_data_mappings.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_types.bal
Update endpoint to support ballerina beta1. …
> Update endpoint to support ballerina beta1

- README.md
- twitter/tests/test.bal
- twitter/twitter_types.bal
> Test file changes

- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_types.bal
> Readme file changes

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/twitter_connector.bal
- twitter/twitter_constants.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_types.bal
Add constant file, Rename getClient() to getCallerActions() and .md file change.
> Link to the PR for changes to the training …
> Add constant file, Rename getClient() to getCallerActions() and .md file change

- Ballerina.toml
Update Ballerina.toml file.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Update Ballerina.toml file

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_utils.bal
Add changes to support Ballerina beta10. …
> Add changes to support Ballerina beta10

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/twitter_data_mappings.bal
- twitter/twitter_types.bal
> Add Doc changes

- README.md
- twitter/Package.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
Add formatting changes.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Add formatting changes

- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
Refactor to support beta14 and add Package.md changes. …
> Refactor to support beta14 and add Package.md changes

- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
> Package.md changes

- twitter/twitter_connector.bal
Connector file formatting change.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
> Connector file formatting change

- twitter/Package.md
Tested the procedure and updated the steps accordingly. Copy edited.
> Copy edit and test steps

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
> Update markdown files

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
> Doc file changes

- Ballerina.toml
- twitter/Package.md
Package.md file change.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Package.md file change

- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_endpoint.bal
> Add changes to support ballerina 0.974.1

- .ballerina/.gitignore
- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_data_mappings.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_types.bal
- twitter/twitter_utils.bal
> Add changes for ballerina v0.975.0 compatibility

- Ballerina.toml
- twitter/Package.md
> Update package.md and toml version

- Ballerina.toml
- twitter/Package.md
Fixes https://github.com/ballerina-platform/ballerina-www/issues/969
> Fix package.md

- twitter/twitter_connector.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_types.bal
This PR fixes syntax issues in the package.
> Fix syntax issues

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
Update markdown files and toml file for 0.980.0 release
> Prepare connector for Ballerina 0.980.0 release

- twitter/tests/test.bal
- twitter/twitter_connector.bal
- twitter/twitter_types.bal
Add parameter to specify the number of tweets required in the search response
> Link to the PR for changes to the training …
> Add parameter to specify the number of tweets required in the search response

- .travis.yml
- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
> Update Twitter connector for 0.981.0 stable release
> Update for 0.981.0 release

- Ballerina.toml
- README.md
- twitter/Package.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_data_mappings.bal
- twitter/twitter_types.bal
Fix connector with latest ballerina changes. …
> Fix connector with latest ballerina changes

- Ballerina.toml
- README.md
- twitter/Module.md
- twitter/tests/README.md
Sync with ballerina 0.983.0
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
> Sync with ballerina 0.983.0

- Ballerina.toml
- twitter/Module.md
- Fix markdown and update toml version
> Release for Ballerina 0.990.0 RC3

- README.md
> Fix module-twitter README.md

- Ballerina.toml
- README.md
- twitter/Module.md
- twitter/tests/README.md
- twitter/twitter_endpoint.bal
- twitter/twitter_utils.bal
> Fix connector for Ballerina 0.990.3

- Ballerina.toml
- README.md
- twitter/Module.md
> Fix code samples in the README.md

- README.md
- twitter/Module.md
- twitter/tests/README.md
- twitter/tests/test.bal
- twitter/twitter_utils.bal
> Sync with ballerina 0.991.0

- Ballerina.toml
- twitter/tests/test.bal
- twitter/twitter_data_mappings.bal
- twitter/twitter_endpoint.bal
- twitter/twitter_types.bal
- twitter/twitter_utils.bal
> Sync with latest Ballerina changes

- Ballerina.toml
- src/twitter/Module.md
- src/twitter/tests/test.bal
> Remove clientConfig's value from the md and test file
